### PR TITLE
added SingleOrder, addedroute to app.js, added getOrder and getAllOrd…

### PR DESCRIPTION
**Pull request by spencersharpe-dev**
…ers in index.js api, added post request for orders. issue #64 #72

### CODE REVIEW

**Review by zachgarrett24 — DISMISSED** [review]
Thumbs up!

**Review by zachgarrett24 — DISMISSED** [review]
yyeeeewwww!

**Review by tillyninjaspace — DISMISSED** [review]
Looks good

**Review by zachgarrett24 — APPROVED** [review]
zzzzzzz

**Pull request merged**
